esphome:
  name: radiator
  friendly_name: Radiator

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "wRTUy/+Rvd+g9WyIJ04IPoQG6/E6RUbjflJGewkrDmk="

ota:
  - platform: esphome
    password: "8a56e9321f2705bbffd01e09861abe28"

wifi:
  ssid: "!secret wifi_ssid"
  password: "!secret wifi_password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Radiator Fallback Hotspot"
    password: "oQtb9IyvAuEf"

captive_portal:

# ────────────────────────────────────────────────────────────────
# I2C bus (for SHT40)
# ────────────────────────────────────────────────────────────────
i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true

# ────────────────────────────────────────────────────────────────
# UART (for TMC2209 smart monitoring)
# ────────────────────────────────────────────────────────────────
uart:
  id: uart_bus
  baud_rate: 115200
  tx_pin: GPIO17
  rx_pin: GPIO16

# ────────────────────────────────────────────────────────────────
# Sensors (SHT40 + Valve %)
# ────────────────────────────────────────────────────────────────
sensor:
  - platform: sht4x
    temperature:
      id: room_temp
      name: "Radiator Temperature"
    humidity:
      id: room_humidity
      name: "Radiator Humidity"
    address: 0x44
    update_interval: 10s

external_components:
  - source:
      type: local
      path: ../esphome/components
    components: [radiator_ctrl]

# or for remote repo:
# external_components:
#  - source:
#      type: git
#      url: https://github.com/hacknus/diy-smart-radiator
#      ref: main
#    refresh: 1min
#    components: [radiator_ctrl]


# Let Home Assistant set a target
number:
  - platform: template
    id: target_temp
    name: "Target Temperature"
    min_value: 15
    max_value: 24
    step: 0.1
    optimistic: true

radiator_ctrl:
  id: my_radiator
  step_pin: GPIO0
  dir_pin: GPIO1
  uart_id: uart_bus
  display_mosi_pin: GPIO18
  display_clk_pin: GPIO19
  display_cs_pin: GPIO2
  display_dc_pin: GPIO21
  display_rst_pin: GPIO14
  enable_pin: GPIO13
